import { AnimatePresence, motion } from "motion/react";
import { IconMenu2, IconX } from "@tabler/icons-react";
import React, { createContext, useContext, useState } from "react";
import { Link } from "react-router-dom";
import { cn } from "@/lib/utils";

type LinkItem = { label: string; href: string; icon: React.ReactNode };
type ContextValue = { open: boolean; setOpen: React.Dispatch<React.SetStateAction<boolean>>; animate: boolean };
const SidebarContext = createContext<ContextValue | undefined>(undefined);
export const useSidebar = () => { const context = useContext(SidebarContext); if (!context) throw new Error("Sidebar must be used inside SidebarProvider"); return context; };
export function SidebarProvider({ children, open: controlledOpen, setOpen: controlledSetOpen, animate = true }: { children: React.ReactNode; open?: boolean; setOpen?: React.Dispatch<React.SetStateAction<boolean>>; animate?: boolean }) { const [internalOpen, setInternalOpen] = useState(false); return <SidebarContext.Provider value={{ open: controlledOpen ?? internalOpen, setOpen: controlledSetOpen ?? setInternalOpen, animate }}>{children}</SidebarContext.Provider>; }
export function Sidebar({ children, ...props }: React.ComponentProps<typeof SidebarProvider>) { return <SidebarProvider {...props}>{children}</SidebarProvider>; }
export function SidebarBody({ children, className }: { children: React.ReactNode; className?: string }) { return <><DesktopSidebar className={className}>{children}</DesktopSidebar><MobileSidebar className={className}>{children}</MobileSidebar></>; }
function DesktopSidebar({ children, className }: { children: React.ReactNode; className?: string }) { const { open, setOpen, animate } = useSidebar(); return <motion.aside onMouseEnter={() => setOpen(true)} onMouseLeave={() => setOpen(false)} animate={{ width: animate ? (open ? 248 : 68) : 248 }} className={cn("sticky top-0 hidden h-svh max-h-svh shrink-0 overflow-hidden border-r border-line bg-panel md:flex md:flex-col", className)}>{children}</motion.aside>; }
function MobileSidebar({ children, className }: { children: React.ReactNode; className?: string }) { const { open, setOpen } = useSidebar(); return <div className="md:hidden"><button aria-label="Open navigation" onClick={() => setOpen(true)} className="fixed left-4 top-4 z-40 border border-line bg-panel p-2 text-copy"><IconMenu2 size={20} /></button><AnimatePresence>{open && <motion.aside initial={{ x: -280 }} animate={{ x: 0 }} exit={{ x: -280 }} transition={{ duration: .2 }} className={cn("fixed inset-y-0 left-0 z-50 flex w-72 flex-col border-r border-line bg-panel", className)}><button aria-label="Close navigation" onClick={() => setOpen(false)} className="absolute right-4 top-4 text-muted"><IconX size={20} /></button>{children}</motion.aside>}</AnimatePresence></div>; }
export function SidebarLink({ link, active }: { link: LinkItem; active?: boolean }) { const { open, setOpen } = useSidebar(); return <Link to={link.href} onClick={() => setOpen(false)} className={cn("flex items-center gap-3 border-l-2 px-5 py-3 text-sm transition-colors", active ? "border-lime bg-[#20251c] text-lime" : "border-transparent text-muted hover:bg-[#202123] hover:text-copy")}>{link.icon}<motion.span animate={{ opacity: open ? 1 : 0, width: open ? "auto" : 0 }} className="overflow-hidden whitespace-nowrap">{link.label}</motion.span></Link>; }
