import { useState } from "react";
import { IconX } from "@tabler/icons-react";
import { api } from "@/lib/api";
import type { Product, ReorderRequest, ReorderRequestInput, ReorderStatus } from "@/types/product";

const statuses: ReorderStatus[] = ["Draft", "Requested", "Ordered", "Received", "Cancelled"];

export function ReorderRequestModal({ product, value, onClose, onSaved }: { product?: Product; value?: ReorderRequest; onClose: () => void; onSaved: () => void }) {
  const [form, setForm] = useState<ReorderRequestInput>(value ? { productId: value.productId, productName: value.productName, supplier: value.supplier, quantity: value.quantity, status: value.status, notes: value.notes } : { productId: product!.id, productName: product!.name, supplier: product!.supplier, quantity: Math.max(10 - product!.stockQuantity, 1), status: "Draft", notes: "" });
  const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const update = (key: keyof ReorderRequestInput, next: string | number) => setForm((current) => ({ ...current, [key]: next }));
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(""); try { value ? await api.updateReorder(value.id, form) : await api.createReorder(form); onSaved(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to save reorder request"); setSaving(false); } };
  return <div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><div role="dialog" aria-modal="true" aria-labelledby="reorder-form-title" className="w-full max-w-lg rounded-lg border border-line bg-panel p-6"><div className="mb-6 flex items-center justify-between"><h2 id="reorder-form-title" className="text-lg font-semibold text-copy">{value ? "Edit reorder request" : "Create reorder request"}</h2><button aria-label="Close reorder request" onClick={onClose} className="text-muted hover:text-copy"><IconX size={19} /></button></div><form onSubmit={submit} className="grid gap-4"><div className="grid gap-2 text-xs text-muted">Product<input readOnly value={form.productName} className="border border-line bg-ink px-3 py-2 text-sm text-copy" /></div><div className="grid gap-2 text-xs text-muted">Supplier<input required value={form.supplier} onChange={(event) => update("supplier", event.target.value)} className="border border-line bg-ink px-3 py-2 text-sm text-copy outline-none focus:border-lime" /></div><label className="grid gap-2 text-xs text-muted">Reorder quantity<input required min={1} type="number" value={form.quantity} onChange={(event) => update("quantity", Number(event.target.value))} className="border border-line bg-ink px-3 py-2 text-sm text-copy outline-none focus:border-lime" /></label><label className="grid gap-2 text-xs text-muted">Status<select value={form.status} onChange={(event) => update("status", event.target.value as ReorderStatus)} className="border border-line bg-ink px-3 py-2 text-sm text-copy outline-none focus:border-lime">{statuses.map((status) => <option key={status}>{status}</option>)}</select></label><label className="grid gap-2 text-xs text-muted">Notes<textarea value={form.notes} onChange={(event) => update("notes", event.target.value)} rows={3} className="resize-none border border-line bg-ink px-3 py-2 text-sm text-copy outline-none focus:border-lime" /></label>{error && <p role="alert" className="text-sm text-coral">{error}</p>}<div className="flex justify-end gap-3 border-t border-line pt-5"><button type="button" onClick={onClose} className="border border-line px-4 py-2 text-sm text-muted">Cancel</button><button disabled={saving} className="bg-lime px-4 py-2 text-sm font-semibold text-ink disabled:opacity-50">{saving ? "Saving…" : "Save request"}</button></div></form></div></div>;
}
